#include "hpcmrb.h"

static void
put_header(FILE *fp)
{
  fputs(
      "/* Generated by HPC mruby compiler */\n"
      "#include <stdio.h>\n"
      "#include <stdlib.h>\n"
      "#include \"mruby.n\"\n"
      , fp);
}

static void
put_decl(FILE *fp, HIR *decl)
{
}

mrb_value
hpc_generate_code(hpc_state *s, FILE *fp, HIR *hir, mrbc_context *c)
{
  puts("Generating C-program...");
  put_header(fp);

  //while (hir) {
  //  put_decl(fp, hir->car);
  //  hir = hir->cdr;
  //}

  return mrb_fixnum_value(0);
}
